<?php /* Smarty version 2.6.27, created on 2016-06-06 06:47:20 compiled from modules/users/usersEdit.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'in_array', 'modules/users/usersEdit.tpl', 52, false),)), $this); ?><h2>Редактирование пользователя <?php echo $this->_tpl_vars['obj']['user']->username; ?> <?php if ($this->_tpl_vars['obj']['id_group'] == 2): ?><a onclick="confirm('Удалить пользователя? Это дейтсвие необратимо!') ? this.href='/admin/users/delete/<?php echo $this->_tpl_vars['obj']['user']->id; ?>
/' : false;" class="btn btn-mini" >Удалить</a><?php endif; ?></h2><form class="form-horizontal" method="POST" action=""> <?php if ($this->_tpl_vars['obj']['message'] !== FALSE): ?><div style="background: #dfdece; margin: 15px; padding: 25px; border: 1px solid #000; border-radius: 15px 15px 15px 15px;"><?php echo $this->_tpl_vars['obj']['message']; ?></div><?php else: ?> <?php $_from = $this->_tpl_vars['obj']['form']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['form']):
?> <?php if ($this->_tpl_vars['form']['type'] != 'hidden'): ?><div class="control-group"><label class="control-label"><?php echo $this->_tpl_vars['form']['name']; ?>
</label><div class="controls"><?php endif; ?> <?php if ($this->_tpl_vars['form']['type']): ?> <?php if ($this->_tpl_vars['form']['type'] != 'select'): ?> <input type="<?php echo $this->_tpl_vars['form']['type']; ?>
" name="<?php echo $this->_tpl_vars['form']['id']; ?>
" value="<?php echo $this->_tpl_vars['form']['value']; ?>
"> <?php else: ?> <select name="<?php echo $this->_tpl_vars['form']['id']; ?>
"> <option>Выберите <?php echo $this->_tpl_vars['form']['name']; ?>
</option> <?php if (! empty ( $this->_tpl_vars['form']['vars'] )): ?> <?php $_from = $this->_tpl_vars['form']['vars']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['cat']):
?> <option value="<?php echo $this->_tpl_vars['cat']['id']; ?>
"<?php if ($this->_tpl_vars['cat']['id'] == $this->_tpl_vars['form']['value']): ?>selected<?php endif; ?>><?php echo $this->_tpl_vars['cat']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> <?php endif; ?> </select> <?php endif; ?> <?php else: ?> <?php echo $this->_tpl_vars['form']['value']; ?> <?php endif; ?> <?php if ($this->_tpl_vars['form']['type'] != 'hidden'): ?></div></div><?php endif; ?> <?php endforeach; endif; unset($_from); ?> <?php if (! empty ( $this->_tpl_vars['obj']['patternsListArr'] )): ?><div class="control-group"><label class="control-label">Выберите шаблон из списка</label><div class="controls"><select name="id_patterns[]"> <option>Не выбран</option> <?php $_from = $this->_tpl_vars['obj']['patternsListArr']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['piece']):
?> <option value="<?php echo $this->_tpl_vars['piece']['id']; ?>
" <?php if (! empty ( $this->_tpl_vars['obj']['userPatterns'] ) && ((is_array($_tmp=$this->_tpl_vars['piece']['id'])) ? $this->_run_mod_handler('in_array', true, $_tmp, $this->_tpl_vars['obj']['userPatterns']) : in_array($_tmp, $this->_tpl_vars['obj']['userPatterns']))): ?>selected="selected"<?php endif; ?>><?php echo $this->_tpl_vars['piece']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> </select></div></div><?php endif; ?> <?php if (! empty ( $this->_tpl_vars['obj']['advertsListArr'] )): ?><div class="control-group"><label class="control-label">Выберите рекламу из списка</label><div class="controls"><select name="id_adverts[]" multiple> <?php $_from = $this->_tpl_vars['obj']['advertsListArr']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['piece']):
?> <option value="<?php echo $this->_tpl_vars['piece']['id']; ?>
" <?php if (! empty ( $this->_tpl_vars['obj']['userAdverts'] ) && ((is_array($_tmp=$this->_tpl_vars['piece']['id'])) ? $this->_run_mod_handler('in_array', true, $_tmp, $this->_tpl_vars['obj']['userAdverts']) : in_array($_tmp, $this->_tpl_vars['obj']['userAdverts']))): ?>selected="selected"<?php endif; ?>><?php echo $this->_tpl_vars['piece']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> </select></div></div><?php endif; ?><div class="control-group"><div class="controls"><input class="btn" type="submit" name="submit" value="Сохранить"></div></div></form> <?php endif; ?>