<?php /* Smarty version 2.6.27, created on 2014-06-28 08:40:52 compiled from modules/products/productsEdit.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'date_format', 'modules/products/productsEdit.tpl', 78, false),)), $this); ?>
<?php if (! empty ( $_GET['fromsite'] )): ?><div id="cboxInner"><form action="<?php echo $_SERVER['REQUEST_URI']; ?>
" method="POST" enctype="multipart/form-data"> <input type="hidden" name="id" value="<?php echo $this->_tpl_vars['obj']['items']['id']; ?>
"><div class="cboxInner-header"><h2 class="cboxInner-title">Редактирование секрета <b>#<?php echo $this->_tpl_vars['obj']['items']['id']; ?>
</b></h2></div><?php if (! empty ( $this->_tpl_vars['obj']['msg'] )): ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'ok'): ?><div class="message message-sucess">Спасибо. Секрет обновлен!</div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'err'): ?><div class="message message-error">Ошибка при обновлении секрета, возможно не заполнены обязательные поля!</div><?php endif; ?> <?php endif; ?><div class="cboxInner-content"><div class="form-item"><div class="label">Категория</div><div class="value"><select name="category" id="whisper-category" data-placeholder="Выберите категорию..."> <?php $_from = $this->_tpl_vars['cats']['parent'][$this->_tpl_vars['obj']['items']['cityID']]; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['piece']):
?> <option value="<?php echo $this->_tpl_vars['piece']['id']; ?>
" <?php if ($this->_tpl_vars['piece']['id'] == $this->_tpl_vars['obj']['items']['category']): ?>selected="selected"<?php endif; ?>>#<?php echo $this->_tpl_vars['piece']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> </select></div></div><div class="form-item"><div class="label">Текст</div><div class="value"><textarea name="text" id="whisper-text" cols="30" rows="10"><?php echo $this->_tpl_vars['obj']['items']['text']; ?>
</textarea></div></div><?php if (! empty ( $this->_tpl_vars['obj']['items']['img'] )): ?><div class="form-item"><div class="label">Изображение</div><div class="value"><img src="<?php echo $this->_tpl_vars['obj']['items']['img']; ?>
" /></div></div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['vk'] === TRUE): ?><div class="form-item checkbox-right"><div class="label">Опубликовать в VK</div><div class="value"><input type="checkbox" name="vk_check"></div></div><div class="form-item"><div class="value"><div id="datetimepicker1" class="datetimepicker input-group date input-append"><input data-format="yyyy/MM/dd hh:mm:ss" type="text" name="pdate" value="<?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?>
" /> <span class="add-on"> <i data-time-icon="icon-time" data-date-icon="icon-calendar" class="icon-calendar"></i> <span>серверное время</span> </span></div><?php if (! empty ( $this->_tpl_vars['obj']['items']['vk_publ'] ) && ! empty ( $this->_tpl_vars['obj']['items']['vk_publ_date'] )): ?><div>* дата последней публикации: <?php echo $this->_tpl_vars['obj']['items']['vk_publ_date']; ?> [ серверное время ]</div><?php endif; ?></div><div class="description">(Поставьте галочку что бы отправить в вк)</div></div><?php else: ?><div>Для данного города не указана группа!</div><?php endif; ?><div class="form-item checkbox-right"><div class="label">Показывать на сайте c:<?php if ($this->_tpl_vars['obj']['items']['approved'] == 0): ?><?php endif; ?></div><div class="value"><input type="checkbox" name="approved"<?php if ($this->_tpl_vars['obj']['items']['approved'] == 1): ?> checked="checked"<?php endif; ?>></div></div><div class="form-item"><div class="value"><?php if ($this->_tpl_vars['obj']['items']['approved'] == 0): ?><div id="datetimepicker1" class="datetimepicker input-group date input-append"><input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="publ_date" value="<?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?>
" /></div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['items']['approved'] == 1): ?> отображается с: <?php echo $this->_tpl_vars['obj']['items']['publ_date']; ?> ( серверное время <?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%z, пояс: %Z") : smarty_modifier_date_format($_tmp, "%z, пояс: %Z")); ?> ) <input type="hidden" name="publ_date" value="<?php echo $this->_tpl_vars['obj']['items']['publ_date']; ?>
" /> <?php endif; ?></div><div class="description">(Поставьте галочку что бы отображать на сайте)</div></div></div><div class="cboxInner-footer"><input type="submit" class="btn btn-green" value="Опубликовать" /> <button class="btn btn-red btn-cbox-close">Закрыть</button></div></form></div><?php else: ?><h2>Редактирование секрета #<?php echo $this->_tpl_vars['obj']['items']['id']; ?> <a onclick="confirm('Удаляем?') ? this.href='/admin/secrets/delete/<?php echo $this->_tpl_vars['obj']['items']['id']; ?>
/' : false;" class="btn btn-mini" >Удалить</a></h2><?php if (! empty ( $this->_tpl_vars['obj']['msg'] )): ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'ok'): ?><div class="alert alert-success">Спасибо. Секрет обновлен!</div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'err'): ?><div class="alert alert-error">Ошибка при обновлении секрета, возможно не заполнены обязательные поля!</div><?php endif; ?> <?php endif; ?> <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="<?php echo $_SERVER['REQUEST_URI']; ?>
"> <input type="hidden" name="id" value="<?php echo $this->_tpl_vars['obj']['items']['id']; ?>
"><div class="control-group"><label class="control-label">Город</label><div class="controls"><?php echo $this->_tpl_vars['obj']['items']['cityName']; ?></div></div><div class="control-group"><label class="control-label">Категория</label><div class="controls"><select name="category" id="" class="chzn"> <?php if ($this->_tpl_vars['IS_ADMIN'] == 1): ?> <?php $_from = $this->_tpl_vars['cats']['items']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['item']):
?> <optgroup label="<?php echo $this->_tpl_vars['item']['title']; ?>
"> <?php $_from = $this->_tpl_vars['item']['child']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['piece']):
?> <option value="<?php echo $this->_tpl_vars['piece']['id']; ?>
" <?php if ($this->_tpl_vars['piece']['id'] == $this->_tpl_vars['obj']['items']['category']): ?>selected="selected"<?php endif; ?>><?php echo $this->_tpl_vars['piece']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> </optgroup> <?php endforeach; endif; unset($_from); ?> <?php else: ?> <?php $_from = $this->_tpl_vars['cats']['parent'][$this->_tpl_vars['obj']['items']['cityID']]; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['piece']):
?> <option value="<?php echo $this->_tpl_vars['piece']['id']; ?>
" <?php if ($this->_tpl_vars['piece']['id'] == $this->_tpl_vars['obj']['items']['category']): ?>selected="selected"<?php endif; ?>><?php echo $this->_tpl_vars['piece']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> <?php endif; ?> </select></div></div><div class="control-group"><label class="control-label">Текст страницы *</label><div class="controls"><textarea name="text" placeholder="Описание продукта"><?php echo $this->_tpl_vars['obj']['items']['text']; ?>
</textarea></div></div><?php if (! empty ( $this->_tpl_vars['obj']['items']['img'] )): ?><div class="control-group"><label class="control-label">Изображение</label><div class="controls"><img src="<?php echo $this->_tpl_vars['obj']['items']['img']; ?>
" /></div></div><?php endif; ?><div class="control-group"><label class="control-label">Опубликовать в VK?</label> <?php if ($this->_tpl_vars['obj']['vk'] === TRUE): ?><div class="controls" id="dpicker"><input type="checkbox" name="vk_check"><div id="datetimepicker2" class="input-append"><input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="pdate" value="<?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?>
" /> <span class="add-on"> <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i> <span>( серверное время )</span> </span></div><?php if (! empty ( $this->_tpl_vars['obj']['items']['vk_publ'] ) && ! empty ( $this->_tpl_vars['obj']['items']['vk_publ_date'] )): ?><div>* дата последней публикации: <?php echo $this->_tpl_vars['obj']['items']['vk_publ_date']; ?> [ серверное время ]</div><?php endif; ?></div><?php else: ?><div class="controls">Для данного города не указана группа!</div><?php endif; ?></div><div class="control-group"><label class="control-label">Показывать на сайте c:<?php if ($this->_tpl_vars['obj']['items']['approved'] == 0): ?><br />(<strong>поставьте галочку что бы отображать на сайте </strong>) <?php endif; ?></label><div class="controls"><input type="checkbox" name="approved"<?php if ($this->_tpl_vars['obj']['items']['approved'] == 1): ?> checked="checked"<?php endif; ?>> <?php if ($this->_tpl_vars['obj']['items']['approved'] == 0): ?><div id="datetimepicker1" class="input-append"><input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="publ_date" value="<?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?>
" /> <span class="add-on"> <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i> <span>( серверное время )</span> </span></div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['items']['approved'] == 1): ?> отображается с: <?php echo $this->_tpl_vars['obj']['items']['publ_date']; ?> ( серверное время <?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%z, пояс: %Z") : smarty_modifier_date_format($_tmp, "%z, пояс: %Z")); ?> ) <input type="hidden" name="publ_date" value="<?php echo $this->_tpl_vars['obj']['items']['publ_date']; ?>
" /> <?php endif; ?></div></div><div class="control-group"><div class="controls" style="border: 1px dotted #000; padding: 12px;"><div>Добавил: <?php echo $this->_tpl_vars['obj']['items']['author_name']; ?></div><div>E-mail: <?php echo $this->_tpl_vars['obj']['items']['author_mail']; ?></div><div>Дата: <?php echo $this->_tpl_vars['obj']['items']['date_add']; ?></div></div></div><div class="control-group"><div class="controls"><input class="btn" type="submit" value="Сохранить" /></div></div></form>
<?php endif; ?>