<?php /* Smarty version 2.6.27, created on 2016-06-06 20:43:31 compiled from modules/static/staticEdit.tpl */ ?><h2>Редактирование текстовой страницы</h2><?php if (! empty ( $this->_tpl_vars['obj']['msg'] )): ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'ok'): ?><div class="alert alert-success">Спасибо. Текстовая страница успешно обновлена!</div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'err'): ?><div class="alert alert-error">Ошибка при обновлении текстовой страницы, возможно не заполнены обязательные поля!</div><?php endif; ?> <?php endif; ?> <form class="form-horizontal" method="POST" action=""><div class="control-group"><label class="control-label">Название*</label><div class="controls"><input id="pageName" type="text" name="title" value="<?php echo $this->_tpl_vars['obj']['items']['title']; ?>
" placeholder="Напишите название страницы"> <?php if ($this->_tpl_vars['obj']['items']['rewrite_name'] <> 'index'): ?><div><label for="chk" class="checkbox"> <input id="chk" type="checkbox" name="translit" value="1" checked="checked" /> Автотранслит(на английский) </label></div><?php endif; ?></div></div><?php if ($this->_tpl_vars['obj']['items']['rewrite_name'] <> 'index'): ?><div class="control-group"><label class="control-label">Link URL*</label><div class="controls"><input type="text" name="rewrite_name" value="<?php echo $this->_tpl_vars['obj']['items']['rewrite_name']; ?>
" placeholder="Напишите Link URL" data-module="nagibaka-translit" data-params="#chk|#pageName|.rwr_name"><div><small>* ссылка: <?php echo $this->_tpl_vars['CI_CONF']['base_url']; ?>
<span class="rwr_name"><?php echo $this->_tpl_vars['obj']['items']['rewrite_name']; ?>
</span>/</small></div></div></div><?php endif; ?> <?php if ($this->_tpl_vars['obj']['items']['rewrite_name'] == 'index'): ?> <input type="hidden" name="rewrite_name" value="<?php echo $this->_tpl_vars['obj']['items']['rewrite_name']; ?>
">
<?php endif; ?><div class="control-group"><label class="control-label">Текст страницы</label><div class="controls"><textarea class="wyciwyg" name="text" placeholder="Текст страницы"><?php echo $this->_tpl_vars['obj']['items']['text']; ?>
</textarea></div></div><div class="control-group"><div class="controls"><input class="btn" type="submit" value="Обновить" /></div></div><input type="hidden" name="id" value="<?php echo $this->_tpl_vars['obj']['items']['id']; ?>
"> </form>
