<?php /* Smarty version 2.6.27, created on 2016-02-08 18:46:35 compiled from modules/products/productsAdd.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'date_format', 'modules/products/productsAdd.tpl', 68, false),)), $this); ?><h2>Добавление секрета</h2><?php if (! empty ( $this->_tpl_vars['obj']['msg'] )): ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'err'): ?><div class="alert alert-error">Произошла ошибка при добавлении секрета. Возможно, заполнены не все обязательные поля!</div><?php else: ?><div class="alert alert-success">Секрет успешно добавлен!<br/>Вы можете перейти к <a href="/admin/secrets/edit/<?php echo $this->_tpl_vars['obj']['lastID']; ?>
/">секрету</a></div><?php endif; ?>
<?php endif; ?> <?php if ($this->_tpl_vars['obj']['msg'] == 'err' || empty ( $this->_tpl_vars['obj']['msg'] )): ?>
<form class="form-horizontal" method="POST" enctype="multipart/form-data" action=""><div class="control-group"><label class="control-label">Категория</label><div class="controls"><select name="category" id="" class="chzn"> <?php $_from = $this->_tpl_vars['cats']['items']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['item']):
?> <optgroup label="<?php echo $this->_tpl_vars['item']['title']; ?>
"> <?php $_from = $this->_tpl_vars['item']['child']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)): foreach ($_from as $this->_tpl_vars['piece']):
?> <option value="<?php echo $this->_tpl_vars['piece']['id']; ?>
" <?php if ($this->_tpl_vars['piece']['id'] == $this->_tpl_vars['obj']['items']['category']): ?>selected="selected"<?php endif; ?>><?php echo $this->_tpl_vars['piece']['title']; ?>
</option> <?php endforeach; endif; unset($_from); ?> </optgroup> <?php endforeach; endif; unset($_from); ?> </select></div></div><div class="control-group"><label class="control-label">Текст секрета*</label><div class="controls"><textarea name="text" placeholder="Описание секрета"><?php echo $this->_tpl_vars['obj']['post']['text']; ?>
</textarea></div></div><div class="control-group"><label class="control-label">Показывать на сайте</label><div class="controls"><input type="checkbox" name="approved" checked="checked"> c: <input type="text" name="pdate" value="<?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?>
"> ( серверное время <?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%z, пояс: %Z") : smarty_modifier_date_format($_tmp, "%z, пояс: %Z")); ?> )</div></div><div class="control-group"><div class="controls"><input class="btn" type="submit" value="Добавить секрет" /></div></div></form> <?php endif; ?>